import { NextRequest, NextResponse } from "next/server";
import { GET as getOpenApi } from "@/app/api/openapi.json/route";
import { env, configWarnings } from "@/lib/utils";
import { redisStatus } from "@/lib/utils";

export const dynamic = "force-dynamic";

export async function GET(req: NextRequest) {
  const authHeader = req.headers.get("authorization");

  if (!env.CRON_SECRET || authHeader !== `Bearer ${env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const errors: string[] = [];
  const baseUrl = env.APP_URL;

  // Cache failures degrade silently — every read falls through to Firestore at
  // full cost while the app still looks healthy. Only a probe surfaces it.
  const cache = await redisStatus();
  if (cache.state === "error") {
    errors.push(`Redis Error: cache is configured but unreachable — ${cache.detail}`);
  }

  const warnings = configWarnings();

  try {
    // Consequential ops must stay flagged or the ChatGPT UI regression returns.
    const openApiRes = await getOpenApi();
    const schema = await openApiRes.json();
    
    for (const [path, methods] of Object.entries(schema.paths || {})) {
      for (const [method, operation] of Object.entries(methods as any)) {
        if (['post', 'patch', 'delete'].includes(method)) {
          if ((operation as any)["x-openai-isConsequential"] !== false) {
            errors.push(`Schema Error: ${method.toUpperCase()} ${path} is missing 'x-openai-isConsequential: false'`);
          }
        }
      }
    }

    const testToken = process.env.CRON_TEST_TOKEN;
    if (testToken) {
      const headers = {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${testToken}`
      };

      const postRes = await fetch(`${baseUrl}/api/expenses`, {
        method: "POST",
        headers,
        body: JSON.stringify({
          title: "__CRON_TEST__",
          amount: 1,
          category: "Test",
          date: new Date().toISOString().split("T")[0],
          notes: "Automated Integration Test"
        })
      });

      if (!postRes.ok) {
        errors.push(`E2E POST Error: Returned ${postRes.status} - ${await postRes.text()}`);
      } else {
        const postData = await postRes.json();
        const id = postData.id || postData.results?.[0]?.id; // handles single or batch

        if (id) {
          const patchRes = await fetch(`${baseUrl}/api/expenses/${id}`, {
            method: "PATCH",
            headers,
            body: JSON.stringify({ amount: 2 })
          });
          
          if (!patchRes.ok) {
            errors.push(`E2E PATCH Error: Returned ${patchRes.status} - ${await patchRes.text()}`);
          }

          const delRes = await fetch(`${baseUrl}/api/expenses/${id}`, {
            method: "DELETE",
            headers
          });

          if (!delRes.ok) {
            errors.push(`E2E DELETE Error: Returned ${delRes.status} - ${await delRes.text()}`);
          }
        } else {
          errors.push(`E2E POST Error: Did not return an ID. Response: ${JSON.stringify(postData)}`);
        }
      }
    } else {
      console.warn("Skipped E2E test: CRON_TEST_TOKEN environment variable is not set.");
    }

  } catch (err: any) {
    errors.push(`Exception during health check: ${err.message}`);
  }

  // No Discord alert here on purpose: this route returns 500 below when it
  // finds errors, and the health-cron workflow already fails on that and
  // posts the response body (including this `errors` array) to Discord.
  // Alerting from both sides would double-notify every 5 minutes.
  if (errors.length > 0) {
    const adminEmail = env.ADMIN_EMAIL;

    if (env.RESEND_API_KEY && adminEmail) {
      const emailHtml = `
        <h2 style="color: #d9534f;">API Health Check Failed!</h2>
        <p>The following errors occurred during the automated health check:</p>
        <ul>
          ${errors.map(e => `<li style="margin-bottom: 8px;"><strong>${e}</strong></li>`).join('')}
        </ul>
        <p style="color: #666; font-size: 12px; margin-top: 20px;">This is an automated alert generated by Continuum Home Health Cron.</p>
      `;

      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: { Authorization: `Bearer ${env.RESEND_API_KEY}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          from: env.CRON_SENDER_EMAIL,
          to: [adminEmail],
          subject: `🚨 API Health Check Alert: ${errors.length} error(s) detected`,
          html: emailHtml,
        }),
      });
    }

    // Fail the GitHub Action step by returning 500
    return NextResponse.json({ success: false, environment: env.ENVIRONMENT, cache: cache.state, warnings, errors }, { status: 500 });
  }

  return NextResponse.json({
    success: true,
    environment: env.ENVIRONMENT,
    cache: cache.state,
    warnings,
    message: "All systems go. Endpoints and schema verified.",
  });
}
